### ISSUE TITLE
Fonts are ugly

### ISSUE THREAD

**Issue by pbuildhouse** [atharva-washimkar/Chess-Application#2]
I am running this project unmodified in Java9 on windows 10 and the fonts are not working properly. Can this be easily fixed?

![Ugly fonts](https://user-images.githubusercontent.com/17983337/38857006-6596d4f8-4228-11e8-8f4a-2b06cf2b0a9b.png)

**Comment by atarw** [comment]
i use a mac, but i'll find a windows computer to test this on and get back to you!

**Comment by pbuildhouse** [comment]
Cool, thanks!

Edit: sorry, just noticed that I added this issue for the wrong project but I figure that the problems are for this project too haha.

**Comment by atarw** [comment]
hey, sorry for the wait, i updated the library to enable anti-aliasing for fonts, so it should look a lot smoother now. let me know if it doesn't!

UPDATE: this issue is 100% fixed as of 06/13/2018, check out the main repository to get the latest version
